### ISSUE TITLE
File names and structures...

### ISSUE THREAD

**Issue by mbaudis** [baudisgroup/segment-liftover#1]
Some changes  to the file should be implemented:

* consistency in headers & some logical structure (e.g. lower case; `sample_id`, `probe_id`, `reference_name`, `segment_start`, `segment_end`)
* I suggest making the "value" columns non-descriptive and open ended; i.e. value[1..n]. I would keep the `value_1`, `value_2` ... example, but allow a undefined numer of columns (one could set a max. like 127, to block run-away data ...)
* I am not sure if we can include the liftover bibnary?
* I'm not happy with the "CNprobes" file name; so maybe just use "probes" (with an internal recognition of `^(?:CN)?probes(?:,chr\w\d?)\.tab$`

**Comment by KyleGao** [comment]
New files will have consistent headers now (replace the old headers):
- for probes: probe_id, chromosome, position
- for segments: segment_id , chromosome, start, end

Other column names are kept the same in new files.

liftover binary is off.

Can specify new files names now, we'll use "segments,cn.tsv" and "probes,cn.tsv"

**Comment by mbaudis** [comment]
> Can specify new files names now, we'll use "segments,cn.tsv" and "probes,cn.tsv"
> 
> 
Yes, let's do this. I'll grep over my source tree, too.
