### ISSUE TITLE
Failed to convert some large convertable segments using UCSC liftOver

### ISSUE THREAD

**Issue by stardustcx** [baudisgroup/segment-liftover#5]
Dear Prof. Gao
I appreciate your responses on previous issue. As my analysis going on, I found another issue that lead to the loss of large convertable segments. It primarily influence chr7 where large normal segments were recorded in our results(see data chunk). They all failed conversion from hg18 to hg19 probably caused by the start position chr7:52912 in hg18 is before the first mappable section(hg18 first map to hg19 is 102995, larger than 52912). These segments are mostly mappable by UCSC liftover that returns the hg19 start position as chr7:10238 (the start position of the first mappable section (chr7:10238) in hg19). I checked the UCSC genome browser in both genomic version and found the conversion is acceptable. So, I hope this feature can be supported in segment_liftover. Also, it may affect the end positions after the last section of a chromosome. This is hard to fix by myself. Please give me a hand. Thanks!

###################### DATA #########################
chr7    52912   6968498
chr7    52912   6536416
chr7    52912   158811019
chr7    52912   22401168
chr7    52912   52981165
chr15   19386005        20088817
chr7    52912   22401168
chr7    52912   22401168
chr15   19406785        20088817
chr7    52912   108398484
chr7    52912   57804817
chr7    52912   8287620
chr7    52912   158811019
chr7    52912   7950554
chr7    141896143       141908979
chr19   23793080        32457816
chr7    52912   6830773
chr7    52912   65204771
chr7    52912   158811019
chr7    52912   57670996
chr7    52912   10690406
chr7    52912   22401168
chr7    52912   4484678
chr7    52912   154024149
chr15   19537068        20013566
chr7    52912   5845530
chr7    52912   8278892
chr7    52912   3239052
chr7    52912   70059571
chr7    52912   22401168
chr7    52912   22401168
chr7    52912   7331134
chr7    142163568       142179254
chr7    52912   2556909
chr7    52912   61818476
chr7    52912   22401168
chr7    52912   141691434
chr7    52912   163647
chr7    52912   3366631
chr7    52912   22401168
chr17   22141081        22550352
chr7    52912   70058626
chr17   22185865        24648652
chr7    52912   38353316
chr7    52912   163647
chr17   22151867        22534030
chr7    52912   26108842
chr7    52912   8098531
chr7    141896143       141909358
chr7    52912   8525444
chr7    52912   76139971
chr7    52912   99376777
chr7    52912   878033
chr24   9253062 10006702
chr7    141699547       141706725
chr24   9253062 10006702
chr24   9253062 10006702
chr24   9253062 10036053
chr7    141699547       141715032
chr24   9253062 10122144
chr7    141699547       141720197
chr7    141720270       141725143
chr7    141699547       141706725
chr7    141699547       141720197
chr7    141699547       141712259
chr7    141699547       141706725
chr24   9253062 10006702
chr7    141699547       141712259
chr24   9253062 10006702
chr24   9253062 10006702
chr7    141699547       141706725
chr7    141707985       141891576
chr7    141699547       141715032
chr7    141699547       141706725

**Comment by KyleGao** [comment]
You problem cannot be completely resolved programmatically, some manual work is needed.

From the ```./logs/unconverted.log ``` file, you can observe the reasons of failure.

For record with a "FALSE", it means that the segment was split and re-allocated to different chromosomes, therefore manual checking is needed. I think this is exactly the case for chr7: 52912 (and many other records). The region surrounds it was re-assigned to chr16 in hg19.  Unlike UCSC liftover, we decided to leave the decision to the user. For these segments, I would suggest to either use UCSC liftover directly if it gives the desired result or shift the start positions of the input file.

In the log file, the 5th column also helps to understand why conversion failed. If it's a negative number, it means the original segment was split into pieces and the order of those pieces changed in the new genome. In this case, human intervention is also needed. 

Lastly, for some records, they can be recovered by loosing the constrains: You can increase parameter --beta. Default value is 2. You can start with 10 for testing.

When lifting over, some segments are just un-liftable.

**Comment by stardustcx** [comment]
Thank you for clarification. I have used larger --beta (up to 100) which indeed converted more. The chr7 can not be resolved this way. So, I will do some manual check. Thank you again.
