### ISSUE TITLE
use of pandas append

### ISSUE THREAD

**Issue by dkoppstein** [baudisgroup/segment-liftover#8]
As of pandas 2.0, pandas concat replaces append. Since the pandas version is not specified in the setup, the latest version is used as a default, which occasionally leads segment_liftover to fail.

**Comment by KyleGao** [comment]
Thank you for pointing this out! I have added the requirement to Pandas.

**Comment by au323** [comment]
Firstly, thanks a lot for creating this tool,  has been a lifesaver. 
I have been facing some issues when using this tool recently. I get an error message while I am converting hg38 build segmental file to hg19 build. Here is the message:
ERROR - sh: ['./liftOver', '/home/au323/WGS_data/.tmp/starts.bed', '/home/au323/WGS_data/hg38ToHg19.over.chain.gz', '/home/au323/WGS_data/.tmp/starts_new.bed', '/home/au323/WGS_data/.tmp/starts.unmapped']
2025-08-05 10:09:23,832 - ERROR - Failure in segment: /home/au323/WGS_data/test_Data_hg38.txt
Traceback (most recent call last):
  File "/home/au323/.local/lib/python3.7/site-packages/segment_liftover/segmentLiftover.py", line 291, in convertSegments
    raise RuntimeError(cmd)
RuntimeError: ['./liftOver', '/home/au323/WGS_data/.tmp/starts.bed', '/home/au323/WGS_data/hg38ToHg19.over.chain.gz', '/home/au323/WGS_data/.tmp/starts_new.bed', '/home/au323/WGS_data/.tmp/starts.unmapped']

[test_Data_hg38.txt](https://github.com/user-attachments/files/21601688/test_Data_hg38.txt)
